package textConverter.utils.specializedTypes;

public enum Alphabet {
    A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,
    ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,ZERO,
    EXCLAMATION_MARK,COLON,SEMICOLON,COMMA,APOSTROPHE,MINUS,PLUS,HASHTAG,STAR,SLASH,BACKSLASH,BRACKET_OPEN,BRACKET_CLOSED,SQUARE_BRACKET_OPEN,SQUARE_BRACKET_CLOSED,BRACE_OPEN,BRACE_CLOSED,EQUAL_MARK,PERCENT_MARK,QUOTATION_MARK;
}
